apiVersion: v1
kind: Service
metadata:
  name: authms
  labels:
    app: authms
    tier: frontend
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 7979
  selector:
    app: authms
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authms-ingress
  annotations:
    nginx.org/server-snippet: 'proxy_ssl_verify off;'
    nginx.ingress.kubernetes.io/rewrite-target: '/'
spec:
  rules:
    - host: auth.example.com
      http:
        paths:
          - backend:
              serviceName: authms
              servicePort: 80
            path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authms
  labels:
    app: authms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authms
      tier: frontend
  template:
    metadata:
      labels:
        app: authms
        tier: frontend
    spec:
      containers:
        - name: authms
          image: tahc/authms:1.0.5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 7979
