apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: chat
    tier: service-api
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 7007
  selector:
    app: chat
    tier: service-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chat-ingress
  annotations:
    nginx.org/server-snippet: 'proxy_ssl_verify off;'
    nginx.ingress.kubernetes.io/rewrite-target: '/'
spec:
  rules:
    - host: chat.example.com
      http:
        paths:
          - backend:
              serviceName: chat
              servicePort: 80
            path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
      tier: service-api
  template:
    metadata:
      labels:
        app: chat
        tier: service-api
    spec:
      containers:
        - name: chat
          image: tahc/chat:1.0.5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 7007
